name: flutter_test_cicd
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  firebase_core: ^2.13.0
  flutter:
    sdk: flutter
  get: 4.6.5

dev_dependencies:
  flutter_flavorizr: ^2.1.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flavorizr:
  app:
    android:
    ios:

  flavors:
#FLAVOR DEV
    dev:
      app:
        name: "app dev"
      android:
        applicationId: "com.example.flutter_test_cicd.dev"
      
      ios:
        bundleId: "com.example.flutter_test_cicd.dev"

#FLAVOR PROD
    prod:
      app:
        name: "app prod"

      android:
        applicationId: "com.example.flutter_test_cicd"

      ios:
        bundleId: "com.example.flutter_test_cicd"



flutter:
  uses-material-design: true
