// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo7rPy8xtthjWO0KAJutMTv2DhKelPaN8',
    appId: '1:486012283647:web:d17d5554c10a7f91fe7aca',
    messagingSenderId: '486012283647',
    projectId: 'flutter-test-cicd',
    authDomain: 'flutter-test-cicd.firebaseapp.com',
    storageBucket: 'flutter-test-cicd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtqBe7T1d-1rqRc4pLz4jKpGFT3YeCAmI',
    appId: '1:486012283647:android:e1c539ddec88cc13fe7aca',
    messagingSenderId: '486012283647',
    projectId: 'flutter-test-cicd',
    storageBucket: 'flutter-test-cicd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxeLvIpWL9PKQn3VSrQozlJHdbxQ7N50s',
    appId: '1:486012283647:ios:b1e1411806555a6cfe7aca',
    messagingSenderId: '486012283647',
    projectId: 'flutter-test-cicd',
    storageBucket: 'flutter-test-cicd.appspot.com',
    iosClientId: '486012283647-mavc1it6mjf2bfs2nmta49cgqo5i80k7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTestCicd',
  );
}
